version: '3'

services:
  piano_mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: piano
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: tinyhhj
      MYSQL_PASSWORD: Samsung*99
    ports:
      - 3306:3306
    volumes:
      - volume:/var/lib/mysql


  piano_application:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - piano_mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://piano_mysql:3306/piano?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root 

volumes:
  volume:
