version: '3'
services:
  worker:
        #image: vimagick/youtube-worker
    build: 
      context: ../docker/dockerfiles/youtube/youtube-worker 
      dockerfile: Dockerfile
    links:
      - redis
    volumes:
      - /media/tinyhhj/hdd/yt:/data
    user: 1000:1000

  redis:
    image: redis
    command: redis-server 
    ports:
      - "6379:6379"
