version: '3'

services:
  application_dev:
    build: .
    ports:
      - 8081:8080
    volumes:
      - volume_log_dev:/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/piano_dev?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: r00t 
      SPRING_PROFILES_ACTIVE: dev
      TZ: Asia/Seoul

volumes:
  volume_log_dev:
