version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - volume_mysql:/var/lib/mysql


  application:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/piano?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: r00t 
    volumes:
      - volume_log:/logs
volumes:
  volume_mysql:
  volume_log:
