version: '3'

services:
  transmission:
    image: linuxserver/transmission
    container_name: piano_transmission
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - USER=tinyhhj
      - PASS=Samsung*99
    volumes:
      - /media/tinyhhj/hdd/torrent/config:/config
      - /media/tinyhhj/hdd/torrent/downloads:/downloads
      - /media/tinyhhj/hdd/torrent/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
