version: '3'

services:
  nginx:
    build: 
      context: ../docker/docker-nginx-webdav
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /media/tinyhhj/hdd:/webdav/webdav/media
      - ../:/webdav/webdav/dev
    environment:
      USERNAME: (tinyhhj guest)
      PASSWORD: (admin guest) 
    depends_on:
      - application

